void xuLi3D1();
void VeHinhChuNhatVien(int x, int y, int z, int b, int color);
void LineDDA();
void HeTrucXYZ();
void textWrite(int &x, int &y, char s[], int color);
void textWriteRemove(int &x, int &y, char s[]);
void textWriteln(int &x, int &y, char s[]);
void textReadnumber(int &x, int &y, char s[]);
void LineDDAan(int x1, int y1, int x2, int y2);
void hientoado(int sd, toado2D A[],int couser);
void HinhHopCN();
